custom_config.settings_form:
  path: '/admin/config/custom_config_form/settings'
  defaults:
    _form: '\Drupal\custom_config_form\Form\CustomSettingsForm'
    _title: 'CustomSettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE