<?php

function custom_attach_library_page_attachments(array &$attachments) {

  $path = $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);

  if($path_args[1] == 'custom-attach-js') {
    $attachments['#attached']['library'][] = 'custom_attach_library/libname';
  }

}

/*function custom_attach_library_page_attachments_alter(&$page){

  $path = $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);

  if($path_args[1] == 'custom-attach-js') {
    $page['#attached']['library'][] = 'custom_attach_library/libname';
  }
}*/

/*
function custom_attach_library_preprocess_page(&$variables){
  if ($variables['is_front'] == TRUE) {
    $variables['#attached']['library'][] = 'my-theme/my-library';
  }
}

In TWIG::

// node.html.twig

{% if node.id == 1 %}
  {{ attach_library('my-theme/my-library') }}
{% endif %}

*/