<?php

use Drupal\pass_value_to_js_and_post\Controller\TestController;

function pass_value_to_js_and_post_page_attachments(array &$attachments) {

  //$mydata = \Drupal\pass_value_to_js_and_post\Controller\TestController::content();

  $path = $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);

  if($path_args[1] == 'controller_value_to_hooks') {

      $contentController = new TestController();
      $mydata = $contentController->content();

      //print_r($mydata['#title']);
      //die();

      $attachments['#attached']['library'][] = 'pass_value_to_js_and_post/mylib-js';
      // pass variable to Drupal.Settings
      $attachments['#attached']['drupalSettings']['mydata'] = $mydata['#title'];

  }

}